server:
  port: 8080
  servlet:
    context-path: /fresh
  tomcat:
    max-http-form-post-size: 100MB


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fresh_delivery
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mail:
    host: smtp.qq.com
    port: 465
    username: 2582789555@qq.com
    password: osjciqltcmupecgj
    protocol: smtp
    tls: true
    ssl: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: org.example.freshdeliveryserver.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

kansha:
  salt: ding_hai_shen_zhen